# Por default existem 3 passos a serem cumpridos:
# 1- Passo de build
# 2- Passo de test
# 3- Passo de deploy(entrega)

#imagem a ser usada na tarefa build-stage
image: docker:stable

#parâmetros para que o serviço do docker continue online
services:
#param para rodar uma imagem docker dentro de outro docker, pois o gitlab já usa um docker
- docker:dind 

#executar antes de qualquer script
before_script:
# faz autenticação no dockerhub por meio de variáveis criada em gitlab Configurações -> CI/CD
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 
- docker info 

#tarefa(job)
build-stage:
    # no stage indicamos qual dos 3 passos a tarefa(job) será chamada
    stage: build
    script:
        - docker build -t minha-imagem .
        - docker tag minha-imagem pvreboucas/minha-imagem:latest
        - docker push pvreboucas/minha-imagem:latest
